---
name: Skyline Notification - Partner Skyline Testnet
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      blade_apex_bridge_ref:
        description: The branch/commit from the Blade Apex Bridge
        type: string
        required: true
      build_blade_output:
        description: Build Blade output
        type: string
        required: true
      lint_output:
        description: Lint output
        type: string
        required: true
      fund_skyline_partner_testnet_output:
        description: Fund Skyline Partner Testnet output
        type: string
        required: true
      e2e_skyline_partner_testnet_test_output:
        description: E2E Skyline Partner Testnet Tests output
        type: string
        required: true
      e2e_skyline_solana_partner_testnet_test_output:
        description: E2E Skyline Solana Partner Testnet Tests output
        type: string
        required: true
      defund_skyline_partner_testnet_output:
        description: Defund Skyline Partner Testnet output
        type: string
        required: true
    secrets:
      APEX_SLACK_WEBHOOK_URL:
        required: true

jobs:
  notification:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ inputs.blade_apex_bridge_ref }}
      - name: Short SHA
        id: short_sha
        run: |
          sha=`git rev-parse HEAD`
          echo "full_value=`echo ${sha}`" >> $GITHUB_OUTPUT
          echo "value=`echo ${sha} | cut -c1-7`" >> $GITHUB_OUTPUT
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.APEX_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          succeed_bnt: 'primary'
          failed_bnt: 'danger'
          succeed_job: ':green:'
          failed_job: ':red:'
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Skyline Testnet Tests"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Workflow Run"
                      },
                      "style": "${{ inputs.build_blade_output == '' && inputs.lint_output == '' && inputs.fund_skyline_partner_testnet_output == '' && inputs.e2e_skyline_partner_testnet_test_output == '' && inputs.e2e_skyline_solana_partner_testnet_test_output == '' && inputs.defund_skyline_partner_testnet_output == '' && env.succeed_bnt || env.failed_bnt }}",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Commit: *<https://github.com/${{ github.repository }}/tree/${{ steps.short_sha.outputs.full_value }}|${{ steps.short_sha.outputs.value }}>*"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.build_blade_output == '' && env.succeed_job || env.failed_job }} *Build*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.lint_output == '' && env.succeed_job || env.failed_job }} *Lint*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.fund_skyline_partner_testnet_output == '' && env.succeed_job || env.failed_job }} *Fund Skyline Partner Testnet*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.e2e_skyline_partner_testnet_test_output == '' && env.succeed_job || env.failed_job }} *E2E Skyline Partner Testnet Tests*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.e2e_skyline_solana_partner_testnet_test_output == '' && env.succeed_job || env.failed_job }} *E2E Skyline Solana Partner Testnet Tests*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.defund_skyline_partner_testnet_output == '' && env.succeed_job || env.failed_job }} *Defund Skyline Partner Testnet*"
                    }
                  ]
                }
              ]
            }
