---
name: Skyline Partner Skyline Testnet
on: # yamllint disable-line rule:truthy
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 22 * * *'
  workflow_dispatch:
    inputs:
      blade_apex_bridge_ref:
        description: The branch/commit from the Blade Apex Bridge
        type: string
        required: true
      run_blade_apex_bridge_partner:
        description: Run E2E Tests on Partner Testnet
        type: boolean
        default: true
      notification:
        description: Notification
        type: boolean
        default: true

jobs:
  inputs_check:
    name: Inputs Check
    runs-on: ubuntu-latest
    outputs:
      blade_apex_bridge_ref: ${{ steps.blade_apex_bridge_ref_input_check.outputs.blade_apex_bridge_ref }}
      run_blade_apex_bridge_partner: ${{ steps.partner_input_check.outputs.run_blade_apex_bridge_partner }}
      notification: ${{ steps.notification_input_check.outputs.notification }}
    steps:
      - name: Blade Apex Bridge Ref Input Check
        id: blade_apex_bridge_ref_input_check
        run: |
          if [[ "${{ inputs.blade_apex_bridge_ref }}" == "" ]]; then
            echo "blade_apex_bridge_ref=feat/skyline" >> $GITHUB_OUTPUT
          else
            echo "blade_apex_bridge_ref=${{ inputs.blade_apex_bridge_ref }}" >> $GITHUB_OUTPUT
          fi
      - name: Partner Input Check
        id: partner_input_check
        run: |
          if [[ "${{ inputs.run_blade_apex_bridge_partner }}" != "false" ]]; then
            echo "run_blade_apex_bridge_partner=true" >> $GITHUB_OUTPUT
          else
            echo "run_blade_apex_bridge_partner=false" >> $GITHUB_OUTPUT
          fi   
      - name: Notification Input Check
        id: notification_input_check
        run: |
          if [[ "${{ inputs.notification }}" != "false" ]]; then
            echo "notification=true" >> $GITHUB_OUTPUT
          else
            echo "notification=false" >> $GITHUB_OUTPUT
          fi
  build_blade:
    name: Build Blade
    uses: ./.github/workflows/build.yml
    needs: inputs_check
    with:
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    needs: [inputs_check, build_blade]
    with:
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
  fund_skyline_partner_testnet:
    name: Fund Skyline Partner Testnet
    uses: ./.github/workflows/skyline-e2e-testnet-test.yml
    needs: [build_blade, inputs_check]
    if: needs.inputs_check.outputs.run_blade_apex_bridge_partner == 'true' && !cancelled()
    with:
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
      blade_apex_bridge_version: partner
      make_target: fund-testnet-e2e-skyline-bridge
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      PARTNER_TESTNET_SKYLINE_BRIDGING_API_KEY: ${{ secrets.PARTNER_TESTNET_SKYLINE_BRIDGING_API_KEY }}
      SKYLINE_E2E_TESTNET_WALLET_KEYS_CONTENT: ${{ secrets.SKYLINE_E2E_TESTNET_WALLET_KEYS_CONTENT }}
  e2e_skyline_partner_testnet_test:
    name: E2E Skyline Partner Testnet Tests
    uses: ./.github/workflows/skyline-e2e-testnet-test.yml
    needs: [fund_skyline_partner_testnet, inputs_check]
    if: needs.inputs_check.outputs.run_blade_apex_bridge_partner == 'true' && needs.fund_skyline_partner_testnet.result == 'success' && !cancelled()
    with:
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
      blade_apex_bridge_version: partner
      make_target: test-testnet-e2e-skyline-bridge
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      PARTNER_TESTNET_SKYLINE_BRIDGING_API_KEY: ${{ secrets.PARTNER_TESTNET_SKYLINE_BRIDGING_API_KEY }}
      SKYLINE_E2E_TESTNET_WALLET_KEYS_CONTENT: ${{ secrets.SKYLINE_E2E_TESTNET_WALLET_KEYS_CONTENT }}
  e2e_skyline_solana_partner_testnet_test:
    name: E2E Skyline Solana Partner Testnet Tests
    uses: ./.github/workflows/skyline-e2e-testnet-test.yml
    needs: [fund_skyline_partner_testnet, inputs_check]
    if: needs.inputs_check.outputs.run_blade_apex_bridge_partner == 'true' && needs.fund_skyline_partner_testnet.result == 'success' && !cancelled()
    with:
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
      blade_apex_bridge_version: partner
      make_target: test-testnet-e2e-skyline-solana
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      PARTNER_TESTNET_SKYLINE_BRIDGING_API_KEY: ${{ secrets.PARTNER_TESTNET_SKYLINE_BRIDGING_API_KEY }}
      SKYLINE_E2E_TESTNET_WALLET_KEYS_CONTENT: ${{ secrets.SKYLINE_E2E_TESTNET_WALLET_KEYS_CONTENT }}
  defund_skyline_partner_testnet:
    name: Defund Skyline Partner Testnet
    uses: ./.github/workflows/skyline-e2e-testnet-test.yml
    needs: [fund_skyline_partner_testnet, e2e_skyline_partner_testnet_test, e2e_skyline_solana_partner_testnet_test, inputs_check]
    if: needs.inputs_check.outputs.run_blade_apex_bridge_partner == 'true' && needs.fund_skyline_partner_testnet.result != 'skipped' && !cancelled()
    with:
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
      blade_apex_bridge_version: partner
      make_target: defund-testnet-e2e-skyline-bridge
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      PARTNER_TESTNET_SKYLINE_BRIDGING_API_KEY: ${{ secrets.PARTNER_TESTNET_SKYLINE_BRIDGING_API_KEY }}
      SKYLINE_E2E_TESTNET_WALLET_KEYS_CONTENT: ${{ secrets.SKYLINE_E2E_TESTNET_WALLET_KEYS_CONTENT }}
  notification_skyline_testnet:
    name: Skyline Testnet Notification
    uses: ./.github/workflows/skyline-notification-testnet.yml
    needs: [build_blade, inputs_check, lint, fund_skyline_partner_testnet, e2e_skyline_partner_testnet_test, e2e_skyline_solana_partner_testnet_test, defund_skyline_partner_testnet]
    if: needs.inputs_check.outputs.notification == 'true' && !cancelled()
    with:
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
      build_blade_output: ${{ needs.build_blade.outputs.workflow_output }}
      lint_output: ${{ needs.lint.outputs.workflow_output }}
      fund_skyline_partner_testnet_output: ${{ needs.fund_skyline_partner_testnet.outputs.workflow_output }}
      e2e_skyline_partner_testnet_test_output: ${{ needs.e2e_skyline_partner_testnet_test.outputs.workflow_output }}
      e2e_skyline_solana_partner_testnet_test_output: ${{ needs.e2e_skyline_solana_partner_testnet_test.outputs.workflow_output }}
      defund_skyline_partner_testnet_output: ${{ needs.defund_skyline_partner_testnet.outputs.workflow_output }}
    secrets:
      APEX_SLACK_WEBHOOK_URL: ${{ secrets.APEX_SLACK_WEBHOOK_URL }}
